# Obras de musica classica do rodizio: (compositor, obra, ano, periodo).
# Para incluir uma obra, acrescente uma linha. O bot nao repete ate passar por todas.
OBRAS = [
    # Barroco
    ("Johann Sebastian Bach", "Tocata e Fuga em Ré menor, BWV 565", "c. 1704", "Barroco"),
    ("Johann Sebastian Bach", "Concertos de Brandemburgo", "1721", "Barroco"),
    ("Johann Sebastian Bach", "Variações Goldberg", "1741", "Barroco"),
    ("Johann Sebastian Bach", "Suíte para Violoncelo nº 1, BWV 1007", "c. 1720", "Barroco"),
    ("Johann Sebastian Bach", "Paixão segundo São Mateus", "1727", "Barroco"),
    ("Johann Sebastian Bach", "Chacona da Partita nº 2 para violino", "c. 1720", "Barroco"),
    ("Antonio Vivaldi", "As Quatro Estações", "1725", "Barroco"),
    ("George Frideric Handel", "Messias", "1742", "Barroco"),
    ("George Frideric Handel", "Música Aquática", "1717", "Barroco"),
    ("George Frideric Handel", "Música para os Reais Fogos de Artifício", "1749", "Barroco"),
    ("Johann Pachelbel", "Cânone em Ré maior", "c. 1680", "Barroco"),
    ("Henry Purcell", "Dido e Enéas", "c. 1689", "Barroco"),
    ("Claudio Monteverdi", "L'Orfeo", "1607", "Barroco"),
    ("Tomaso Albinoni", "Concerto para oboé em Ré menor, Op. 9 nº 2", "1722", "Barroco"),
    ("Domenico Scarlatti", "Sonata em Ré menor, K. 141", "séc. XVIII", "Barroco"),
    ("Jean-Philippe Rameau", "Les Indes galantes", "1735", "Barroco"),
    ("Giovanni Battista Pergolesi", "Stabat Mater", "1736", "Barroco"),
    # Classico
    ("Wolfgang Amadeus Mozart", "Eine kleine Nachtmusik", "1787", "Clássico"),
    ("Wolfgang Amadeus Mozart", "Réquiem em Ré menor", "1791", "Clássico"),
    ("Wolfgang Amadeus Mozart", "A Flauta Mágica", "1791", "Clássico"),
    ("Wolfgang Amadeus Mozart", "Sinfonia nº 40", "1788", "Clássico"),
    ("Wolfgang Amadeus Mozart", "Sinfonia nº 41 (Júpiter)", "1788", "Clássico"),
    ("Wolfgang Amadeus Mozart", "Concerto para piano nº 21", "1785", "Clássico"),
    ("Wolfgang Amadeus Mozart", "Concerto para clarinete", "1791", "Clássico"),
    ("Wolfgang Amadeus Mozart", "As Bodas de Fígaro", "1786", "Clássico"),
    ("Wolfgang Amadeus Mozart", "Don Giovanni", "1787", "Clássico"),
    ("Joseph Haydn", "Sinfonia nº 94 (Surpresa)", "1791", "Clássico"),
    ("Joseph Haydn", "Sinfonia nº 45 (Adeus)", "1772", "Clássico"),
    ("Joseph Haydn", "A Criação", "1798", "Clássico"),
    ("Joseph Haydn", "Quarteto de cordas Op. 76 nº 3 (Imperador)", "1797", "Clássico"),
    ("Christoph Willibald Gluck", "Orfeu e Eurídice", "1762", "Clássico"),
    ("Ludwig van Beethoven", "Sinfonia nº 5", "1808", "Clássico/Romântico"),
    ("Ludwig van Beethoven", "Sinfonia nº 9", "1824", "Clássico/Romântico"),
    ("Ludwig van Beethoven", "Sinfonia nº 3 (Eroica)", "1804", "Clássico/Romântico"),
    ("Ludwig van Beethoven", "Sinfonia nº 6 (Pastoral)", "1808", "Clássico/Romântico"),
    ("Ludwig van Beethoven", "Sinfonia nº 7", "1812", "Clássico/Romântico"),
    ("Ludwig van Beethoven", "Sonata ao Luar", "1801", "Clássico/Romântico"),
    ("Ludwig van Beethoven", "Sonata Patética", "1798", "Clássico/Romântico"),
    ("Ludwig van Beethoven", "Sonata Appassionata", "1805", "Clássico/Romântico"),
    ("Ludwig van Beethoven", "Für Elise", "1810", "Clássico/Romântico"),
    ("Ludwig van Beethoven", "Concerto para piano nº 5 (Imperador)", "1811", "Clássico/Romântico"),
    ("Ludwig van Beethoven", "Concerto para violino", "1806", "Clássico/Romântico"),
    # Romantico
    ("Franz Schubert", "Sinfonia Inacabada", "1822", "Romântico"),
    ("Franz Schubert", "Winterreise", "1827", "Romântico"),
    ("Franz Schubert", "Ave Maria (Ellens dritter Gesang)", "1825", "Romântico"),
    ("Franz Schubert", "Quinteto A Truta", "1819", "Romântico"),
    ("Franz Schubert", "Erlkönig", "1815", "Romântico"),
    ("Felix Mendelssohn", "Sonho de uma Noite de Verão", "1842", "Romântico"),
    ("Felix Mendelssohn", "Concerto para violino em Mi menor", "1844", "Romântico"),
    ("Felix Mendelssohn", "Abertura As Hébridas", "1830", "Romântico"),
    ("Frédéric Chopin", "Noturno Op. 9 nº 2", "1832", "Romântico"),
    ("Frédéric Chopin", "Balada nº 1", "1835", "Romântico"),
    ("Frédéric Chopin", "Estudo Revolucionário", "1831", "Romântico"),
    ("Frédéric Chopin", "Polonaise Heroica", "1842", "Romântico"),
    ("Frédéric Chopin", "Fantasia-Improviso", "1834", "Romântico"),
    ("Frédéric Chopin", "Concerto para piano nº 1", "1830", "Romântico"),
    ("Robert Schumann", "Kinderszenen (Träumerei)", "1838", "Romântico"),
    ("Robert Schumann", "Concerto para piano em Lá menor", "1845", "Romântico"),
    ("Robert Schumann", "Dichterliebe", "1840", "Romântico"),
    ("Franz Liszt", "Liebestraum nº 3", "1850", "Romântico"),
    ("Franz Liszt", "Rapsódia Húngara nº 2", "1847", "Romântico"),
    ("Franz Liszt", "La Campanella", "1851", "Romântico"),
    ("Franz Liszt", "Sonata em Si menor", "1853", "Romântico"),
    ("Franz Liszt", "Les Préludes", "1854", "Romântico"),
    ("Franz Liszt", "Consolação nº 3", "1850", "Romântico"),
    ("Hector Berlioz", "Sinfonia Fantástica", "1830", "Romântico"),
    ("Richard Wagner", "Cavalgada das Valquírias", "1856", "Romântico"),
    ("Richard Wagner", "Prelúdio de Tristão e Isolda", "1859", "Romântico"),
    ("Giuseppe Verdi", "La Traviata", "1853", "Romântico"),
    ("Giuseppe Verdi", "Réquiem", "1874", "Romântico"),
    ("Giuseppe Verdi", "Coro dos Escravos Hebreus (Nabucco)", "1842", "Romântico"),
    ("Giuseppe Verdi", "Aida", "1871", "Romântico"),
    ("Gioachino Rossini", "Abertura de Guilherme Tell", "1829", "Romântico"),
    ("Gioachino Rossini", "O Barbeiro de Sevilha", "1816", "Romântico"),
    ("Johannes Brahms", "Dança Húngara nº 5", "1869", "Romântico"),
    ("Johannes Brahms", "Sinfonia nº 4", "1885", "Romântico"),
    ("Johannes Brahms", "Um Réquiem Alemão", "1868", "Romântico"),
    ("Johannes Brahms", "Concerto para violino", "1878", "Romântico"),
    ("Piotr Ilitch Tchaikovsky", "O Lago dos Cisnes", "1876", "Romântico"),
    ("Piotr Ilitch Tchaikovsky", "O Quebra-Nozes", "1892", "Romântico"),
    ("Piotr Ilitch Tchaikovsky", "Abertura 1812", "1880", "Romântico"),
    ("Piotr Ilitch Tchaikovsky", "Sinfonia nº 6 (Patética)", "1893", "Romântico"),
    ("Piotr Ilitch Tchaikovsky", "Concerto para piano nº 1", "1875", "Romântico"),
    ("Piotr Ilitch Tchaikovsky", "Concerto para violino", "1878", "Romântico"),
    ("Antonín Dvořák", "Sinfonia do Novo Mundo", "1893", "Romântico"),
    ("Antonín Dvořák", "Concerto para violoncelo", "1895", "Romântico"),
    ("Edvard Grieg", "Peer Gynt (Na Gruta do Rei da Montanha)", "1875", "Romântico"),
    ("Edvard Grieg", "Concerto para piano em Lá menor", "1868", "Romântico"),
    ("Bedřich Smetana", "O Moldava", "1874", "Romântico"),
    ("Modest Mussorgsky", "Quadros de uma Exposição", "1874", "Romântico"),
    ("Modest Mussorgsky", "Uma Noite no Monte Calvo", "1867", "Romântico"),
    ("Nikolai Rimsky-Korsakov", "Scheherazade", "1888", "Romântico"),
    ("Nikolai Rimsky-Korsakov", "O Voo do Besouro", "1900", "Romântico"),
    ("Georges Bizet", "Carmen", "1875", "Romântico"),
    ("Camille Saint-Saëns", "O Carnaval dos Animais", "1886", "Romântico"),
    ("Camille Saint-Saëns", "Dança Macabra", "1874", "Romântico"),
    ("Camille Saint-Saëns", "Sinfonia nº 3 (Órgão)", "1886", "Romântico"),
    ("Johann Strauss II", "O Danúbio Azul", "1867", "Romântico"),
    ("Giacomo Puccini", "Nessun Dorma (Turandot)", "1926", "Romântico tardio"),
    ("Giacomo Puccini", "La Bohème", "1896", "Romântico tardio"),
    ("Giacomo Puccini", "Madama Butterfly", "1904", "Romântico tardio"),
    ("Gustav Mahler", "Sinfonia nº 5 (Adagietto)", "1902", "Romântico tardio"),
    ("Gustav Mahler", "Sinfonia nº 2 (Ressurreição)", "1894", "Romântico tardio"),
    ("Anton Bruckner", "Sinfonia nº 7", "1883", "Romântico tardio"),
    ("Richard Strauss", "Assim Falou Zaratustra", "1896", "Romântico tardio"),
    ("Richard Strauss", "Quatro Últimas Canções", "1948", "Romântico tardio"),
    ("Sergei Rachmaninoff", "Concerto para piano nº 2", "1901", "Romântico tardio"),
    ("Sergei Rachmaninoff", "Rapsódia sobre um Tema de Paganini", "1934", "Romântico tardio"),
    ("Sergei Rachmaninoff", "Prelúdio em Dó sustenido menor", "1892", "Romântico tardio"),
    ("Jean Sibelius", "Finlândia", "1899", "Romântico tardio"),
    ("Edward Elgar", "Variações Enigma (Nimrod)", "1899", "Romântico tardio"),
    ("Edward Elgar", "Concerto para violoncelo", "1919", "Romântico tardio"),
    ("Gabriel Fauré", "Réquiem", "1890", "Romântico tardio"),
    ("Gabriel Fauré", "Pavane", "1887", "Romântico tardio"),
    ("Niccolò Paganini", "Capricho nº 24", "1817", "Romântico"),
    # Seculo XX
    ("Claude Debussy", "Clair de Lune", "1905", "Impressionismo"),
    ("Claude Debussy", "Prelúdio à Tarde de um Fauno", "1894", "Impressionismo"),
    ("Claude Debussy", "La Mer", "1905", "Impressionismo"),
    ("Maurice Ravel", "Boléro", "1928", "Impressionismo"),
    ("Maurice Ravel", "Pavana para uma Infanta Defunta", "1899", "Impressionismo"),
    ("Maurice Ravel", "Daphnis et Chloé", "1912", "Impressionismo"),
    ("Erik Satie", "Gymnopédie nº 1", "1888", "Moderno"),
    ("Igor Stravinsky", "A Sagração da Primavera", "1913", "Moderno"),
    ("Igor Stravinsky", "O Pássaro de Fogo", "1910", "Moderno"),
    ("Sergei Prokofiev", "Pedro e o Lobo", "1936", "Moderno"),
    ("Sergei Prokofiev", "Dança dos Cavaleiros (Romeu e Julieta)", "1935", "Moderno"),
    ("Dmitri Shostakovich", "Concerto para piano nº 2", "1957", "Moderno"),
    ("Dmitri Shostakovich", "Sinfonia nº 7 (Leningrado)", "1941", "Moderno"),
    ("Gustav Holst", "Os Planetas", "1916", "Moderno"),
    ("Carl Orff", "O Fortuna (Carmina Burana)", "1936", "Moderno"),
    ("Samuel Barber", "Adagio para Cordas", "1936", "Moderno"),
    ("George Gershwin", "Rhapsody in Blue", "1924", "Moderno"),
    ("Aaron Copland", "Appalachian Spring", "1944", "Moderno"),
    ("Heitor Villa-Lobos", "Bachianas Brasileiras nº 5", "1938", "Moderno"),
    ("Heitor Villa-Lobos", "O Trenzinho do Caipira (Bachianas nº 2)", "1930", "Moderno"),
    ("Manuel de Falla", "Dança Ritual do Fogo", "1915", "Moderno"),
    ("Joaquín Rodrigo", "Concierto de Aranjuez", "1939", "Moderno"),
    ("Arvo Pärt", "Spiegel im Spiegel", "1978", "Contemporâneo"),
    ("Philip Glass", "Metamorphosis One", "1988", "Contemporâneo"),
]
